def sum(a: int, b: int) -> int:
    return a + b


# test sum
assert sum(4, 6) == 10, "error, there is something wrong!"  # this message going to show for user in AssertionError
